/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-02-19 09:13:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t<title>Pizza Shop : Menu</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("\t\t<!-- start of header -->\r\n");
      out.write("\t\t<span class=\"signboard\"></span>\r\n");
      out.write("\t\t<ul id=\"infos\">\r\n");
      out.write("\t\t\t<li class=\"home\"><a href=\"Home.jsp\">HOME</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<a href=\"index.html\" id=\"logo\"></a>\r\n");
      out.write("\t\t<ul id=\"navigation\">\r\n");
      out.write("\t\t\t<li><a href=\"Employee.jsp\"><span>Employee</span></a></li>\r\n");
      out.write("\t\t\t<li class=\"main current\"><a href=\"Menu.jsp\"><span>Manu&Order</span></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"Member.jsp\"><span>Member</span></a></li>\r\n");
      out.write("\t\t\t<li><a href=\"Orderlist.jsp\"><span>Orderlist</span></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<!-- /#navigation -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end of header -->\r\n");
      out.write("\t<div id=\"contents\">\r\n");
      out.write("\t\t<!-- start of contents -->\r\n");
      out.write("\t\t<div id=\"menus\">\r\n");
      out.write("\t\t\t<div class=\"card-group\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top img-thumbnail\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/PizzaOrderSystem/images/bacon1.png\" alt=\"Card image cap\"\r\n");
      out.write("\t\t\t\t\t\twidth=\"500\" height=\"500\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">เบคอนซุปเปอร์ดีไลท์</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">พริกหยวก มะเขื่อเทศ แฮม เบคอนแผ่น\r\n");
      out.write("\t\t\t\t\t\t\tไส้กรอกอิตาเลียน มอสซาเรลล่าชีส ซอสพิซซ่า</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<small class=\"text-muted\">319฿</small>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card card-body bgOrder\" style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"chx1\"> Order\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"txt1\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top img-thumbnail\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/PizzaOrderSystem/images/tro1.png\" alt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">ทรอปิคอลซีฟู้ด</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">สัปปะรด ซีฟู้ดมิกซ์ กุ้ง ปูอัด มอสซาเรลล่าชีส ซอสเทาซันไอส์แลนด์</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<small class=\"text-muted\">379฿</small>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card card-body bgOrder\" style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"chx1\"> Order\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"txt1\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top img-thumbnail\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/PizzaOrderSystem/images/Italian-Sausage1.png\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">ไส้กรอกอิตาเลียน</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">เป๊ปเปอโรนี เห็ด หัวหอม มะเขื่อเทศ\r\n");
      out.write("\t\t\t\t\t\t\tไส้กรอกอิตาเลียน มอสซาเรลล่าชีส ซอสพิซซ่า</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<small class=\"text-muted\">319฿</small>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card card-body bgOrder\" style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"chx1\"> Order\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"txt1\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top img-thumbnail\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/PizzaOrderSystem/images/Chicken-Caldo1.png\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">ไก่อบซอส</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">สัปปะรด ไก่ย่าง พริกแดง\r\n");
      out.write("\t\t\t\t\t\t\tพริกเขียวมอสซาเรลล่าชีส ซอสพิซซ่า</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<small class=\"text-muted\">299฿</small>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card card-body bgOrder\" style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"chx1\"> Order\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"txt1\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top img-thumbnail\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/PizzaOrderSystem/images/Hawaiian1.png\" alt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">ฮาวายเอี้ยน</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">สัปปะรด แฮม เบคอนแผ่น มอสซาเรลล่าชีส\r\n");
      out.write("\t\t\t\t\t\t\tซอสพิซซ่า</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<small class=\"text-muted\">319฿</small>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card card-body bgOrder\" style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"chx1\"> Order\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"txt1\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"card-group\">\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top img-thumbnail\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/PizzaOrderSystem/images/chicken1.png\" alt=\"Card image cap\"\r\n");
      out.write("\t\t\t\t\t\twidth=\"500\" height=\"500\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">ชิกเก้นสติ๊ก</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<small class=\"text-muted\">89฿</small>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card card-body bgOrder\" style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"chx1\"> Order\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"txt1\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top img-thumbnail\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/PizzaOrderSystem/images/itm1.png\" alt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">ซี่โครงหมูบาร์บีคิว</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<small class=\"text-muted\">279฿</small>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card card-body bgOrder\" style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"chx1\"> Order\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"txt1\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top img-thumbnail\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/PizzaOrderSystem/images/Nuggets1.png\" alt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">ชิกเก้น นักเก็ตส์ 6 ชิ้น\r\n");
      out.write("\t\t\t\t\t\t\tพร้อมซอสมะเขือเทศ</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<small class=\"text-muted\">79฿</small>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card card-body bgOrder\" style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"chx1\"> Order\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"txt1\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top img-thumbnail\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/PizzaOrderSystem/images/bread1.png\" alt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">ขนมปังกระเทียม</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<small class=\"text-muted\">79฿</small>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card card-body bgOrder\" style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"chx1\"> Order\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"txt1\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top img-thumbnail\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/PizzaOrderSystem/images/Spicy-Wing1.png\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">ปีกไก่สไปซี่เกาหลี 6 ชิ้น</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<small class=\"text-muted\">129฿</small>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card card-body bgOrder\" style=\"display:inline-block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" id=\"chx1\"> Order\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"txt1\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"container\" style=\"padding:10px;\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-outline-success\"></i>Order</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end of contents -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t\t<!-- start of footer -->\r\n");
      out.write("\t\t<ul class=\"advertise\">\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<ul class=\"navigation\">\r\n");
      out.write("\t\t\t\t<li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"booking.html\">Book an event</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"blog.html\">Blog</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"about.html\">About</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"last\"><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end of footer -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
